version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000' # Run server port
      - '5858:5858' # Debug port
    restart: always
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_DB={{projectName}}-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
