# LTS image from docker hub
FROM node:14.18.0-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy local files to the docker image
COPY . /usr/src/app

# Install dependencies
RUN npm install

# Expose the port where the app will run
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "dev" ]
