version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=db_bootstrap
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
